[tasks.lib-test]
command = "cargo"
args = ["test", "--lib", "--tests"]
dependencies = []

[tasks.doc-test]
command = "cargo"
args = ["test", "--doc"]
dependencies = []

[tasks.check-all]
command = "cargo"
args = ["check"]
dependencies = []