[tasks.no_std-test]
command = "cargo"
args = ["test", "--lib", "--tests", "--no-default-features"]
dependencies = []

[tasks.std-test]
command = "cargo"
args = ["test", "--lib", "--tests", "--no-default-features", "--features", "alloc"]
dependencies = []

[tasks.alloc-test]
command = "cargo"
args = ["test", "--lib", "--tests", "--no-default-features", "--features", "std"]
dependencies = []

[tasks.lib-test]
dependencies = [
    'no_std-test',
    'alloc-test',
    'std-test',
]
[tasks.no_std-doc-test]
command = "cargo"
args = ["test", "--doc", "--no-default-features"]
dependencies = []

[tasks.std-doc-test]
command = "cargo"
args = ["test", "--doc", "--no-default-features", "--features", "alloc"]
dependencies = []

[tasks.alloc-doc-test]
command = "cargo"
args = ["test", "--doc", "--no-default-features", "--features", "std"]
dependencies = []

[tasks.doc-test]
dependencies = [
    'no_std-doc-test',
    'alloc-doc-test',
    'std-doc-test',
]

[tasks.no_std_check]
command = "cargo"
args = ["check", "--no-default-features"]
dependencies = []

[tasks.std_check]
command = "cargo"
args = ["check", "--no-default-features", "--features", "alloc"]
dependencies = []

[tasks.alloc_check]
command = "cargo"
args = ["check", "--no-default-features", "--features", "std"]
dependencies = []

[tasks.check-all]
dependencies = [
    'no_std_check',
    'alloc_check',
    'std_check',
]