name: PR test
on: [pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo +nightly test --verbose
      run: cargo +nightly test --verbose --features "nostd"
      run: cargo +nightly test --verbose --features "nostd,alloc"
      run: cargo +nightly test --verbose --features "alloc"
