name: PR test
on: [pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]
        features: ["\"\"", "\"nostd\"", "\"nostd,alloc\"", "\"alloc\""] 

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cd core && cargo +nightly test --verbose --features ${{ matrix.features }}