name: PR test
on: [pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # windows and macos are disabled, because we don't do anything target specific
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        rust: [nightly]
        features: ["\"\"", "--features \"no_std\"", "--features \"no_std,alloc\"", "--features \"alloc\""] 

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cd core;cargo +nightly test --verbose ${{ matrix.features }}
